"""Plain-language labels for the Desk, in English and Hindi (stock Frappe translation files).

Frappe shows record-type names, dropdown values, menu items and script messages through its
translation lookup, in English too. This file is the one place those labels live; it writes
anumati/translations/en.csv and hi.csv. Stored values and APIs never change.

Hindi is a first draft for a named reviewer to check before the pilot. Words Frappe already
translates well (Open, Draft, Today, ...) are left to Frappe.

Edit here, run `python3 tools/gen_labels.py` from the repo root, commit the CSVs."""
import csv, os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "anumati", "translations")

# (source string, English label or None to keep it, Hindi)
RECORD_TYPES = [
    ("Data Principal", "Beneficiary", "लाभार्थी"),
    ("Consent Event", "Consent record", "सहमति रिकॉर्ड"),
    ("Consent State", "Current consent", "वर्तमान सहमति"),
    ("Rights Request", "Request", "अनुरोध"),
    ("ROPA Entry", "Record of processing", "प्रोसेसिंग रिकॉर्ड"),
    ("Purge Request", "Deletion task", "डेटा मिटाने का काम"),
    ("Propagation Ack", "Partner confirmation", "साझेदार की पुष्टि"),
    ("Verification Attempt", "Confirmation attempt", "पुष्टि का प्रयास"),
    ("Channel Provider", "Messaging account", "मैसेजिंग खाता"),
    ("Source System", "Connected system", "जुड़ा हुआ सिस्टम"),
    ("Field Device", "Field phone", "फील्ड फ़ोन"),
    ("Audit Entry", "Audit log entry", "ऑडिट लॉग प्रविष्टि"),
    ("Guardian Link", "Guardian", "अभिभावक"),
    ("Notice Template", "Notice", "सूचना"),
    ("Notice Translation", None, "सूचना का अनुवाद"),
    ("Breach Incident", "Breach", "डेटा उल्लंघन"),
    ("System Usage Log", "Consent check log", "सहमति जाँच लॉग"),
    ("Retention Policy", "Retention rule", "डेटा रखने का नियम"),
    ("Funder Link", "Funder sharing", "फंडर के साथ साझा"),
    ("Audit Share", "Auditor link", "ऑडिटर लिंक"),
    ("Anumati Settings", None, "अनुमति सेटिंग्स"),
    ("Programme", None, "कार्यक्रम"),
    ("Purpose", None, "उद्देश्य"),
    ("Processor", None, "डेटा प्रोसेसर (साझेदार)"),
    ("Data Category", None, "डेटा की श्रेणी"),
    ("Message Template", None, "संदेश टेम्पलेट"),
    ("Campaign", None, "अभियान"),
]

CODES = [
    # how consent was given
    ("self_digital", "Self, on their own phone", "स्वयं, अपने फ़ोन पर"),
    ("self_worker_device", "Self, on the worker's phone", "स्वयं, कार्यकर्ता के फ़ोन पर"),
    ("assisted_verbal", "Assisted: said yes (voice)", "मदद से: बोलकर हाँ"),
    ("assisted_thumbprint", "Assisted: thumbprint", "मदद से: अंगूठे का निशान"),
    ("assisted_witnessed", "Assisted: with a witness", "मदद से: गवाह के साथ"),
    ("guardian_minor", "Guardian, for a child", "अभिभावक, बच्चे के लिए"),
    ("guardian_pwd", "Guardian, for a person with disability", "अभिभावक, दिव्यांग व्यक्ति के लिए"),
    ("paper", "Paper form", "काग़ज़ का फ़ॉर्म"),
    # confirmation
    ("server_otp", "SMS code from Anumati", "अनुमति से SMS कोड"),
    ("device_sms_otp", "SMS code from the worker's phone", "कार्यकर्ता के फ़ोन से SMS कोड"),
    ("reverse_sms", "Reply by SMS", "SMS से जवाब"),
    ("missed_call", "Missed call", "मिस्ड कॉल"),
    ("deferred", "Confirm later by SMS", "बाद में SMS से पुष्टि"),
    ("evidence_only", "Evidence only (no phone)", "सिर्फ़ सबूत (फ़ोन नहीं)"),
    ("captured", "Captured", "दर्ज"),
    ("recorded", "Recorded", "दर्ज किया गया"),
    ("confirmed", "Confirmed", "पुष्टि हो गई"),
    ("unconfirmed", "Waiting for confirmation", "पुष्टि बाकी"),
    # actions and states
    ("grant", "Agreed", "सहमति दी"),
    ("withdraw", "Withdrew", "सहमति वापस ली"),
    ("refuse", "Said no to all", "सब के लिए मना किया"),
    ("renew", "Renewed", "नवीनीकरण"),
    ("granted", "Agreed", "सहमति है"),
    ("withdrawn", "Withdrawn", "वापस ली गई"),
    ("refused", "Said no", "मना किया"),
    ("not_asked", "Not asked", "पूछा नहीं गया"),
    ("expired", "Expired", "समाप्त"),
    # notice delivery
    ("recording", "Played the recording", "रिकॉर्डिंग सुनाई"),
    ("phone_voice", "Phone read it aloud", "फ़ोन ने पढ़कर सुनाया"),
    ("read_aloud", "Worker read it aloud", "कार्यकर्ता ने पढ़कर सुनाया"),
    ("read_on_screen", "Read it on screen", "स्क्रीन पर पढ़ा"),
    # channels
    ("app", "Field app", "फील्ड ऐप"),
    ("hosted_page", "Web page", "वेब पेज"),
    ("connector", "Connected system", "जुड़ा हुआ सिस्टम"),
    ("field_worker", "Field worker", "फील्ड कार्यकर्ता"),
    ("slip", "Paper slip", "पर्ची"),
    ("sms", "SMS", "SMS"),
    ("whatsapp", "WhatsApp", "व्हाट्सऐप"),
    ("ivr", "Phone (IVR)", "फ़ोन (IVR)"),
    ("web", "Website", "वेबसाइट"),
    ("email", "Email", "ईमेल"),
    ("community", "Community meeting", "सामुदायिक बैठक"),
    ("api", "Connected system (API)", "जुड़ा हुआ सिस्टम (API)"),
    ("ussd", "USSD", "USSD"),
    ("device_sms", "SMS from the worker's phone", "कार्यकर्ता के फ़ोन से SMS"),
    ("in_person", "In person", "आमने-सामने"),
    ("field_visit", "Field visit", "फील्ड विज़िट"),
    # request types
    ("withdrawal", "Withdrawal", "सहमति वापसी"),
    ("access", "Data access", "डेटा देखने का अनुरोध"),
    ("correction", "Correction", "सुधार"),
    ("erasure", "Erasure", "डेटा मिटाना"),
    ("grievance", "Grievance", "शिकायत"),
    ("nomination", "Nomination", "नामांकन"),
    # people
    ("beneficiary", "Beneficiary", "लाभार्थी"),
    ("patient", "Patient", "मरीज़"),
    ("student", "Student", "विद्यार्थी"),
    ("employee", "Employee", "कर्मचारी"),
    ("member", "Member", "सदस्य"),
    ("other", "Other", "अन्य"),
    ("under_18", "Under 18", "18 से कम"),
    ("18_plus", "18 or over", "18 या अधिक"),
    ("unknown", "Not known", "पता नहीं"),
    ("self", "Self", "स्वयं"),
    ("spouse", "Spouse", "पति/पत्नी"),
    ("parent", "Parent", "माता/पिता"),
    ("child", "Child", "संतान"),
    ("sibling", "Brother or sister", "भाई/बहन"),
    ("relative", "Relative", "रिश्तेदार"),
    ("neighbour", "Neighbour", "पड़ोसी"),
    ("legal_guardian", "Legal guardian", "क़ानूनी अभिभावक"),
    ("family_pwd", "Family (person with disability)", "परिवार (दिव्यांग व्यक्ति)"),
    ("court", "Court", "अदालत"),
    ("committee", "Committee", "समिति"),
    ("digilocker", "DigiLocker", "डिजीलॉकर"),
    ("document", "Document", "दस्तावेज़"),
    ("witness", "Witness", "गवाह"),
    # campaigns
    ("true_up", "Catch-up", "छूटे लोगों से सहमति"),
    ("re_consent", "Re-consent", "दोबारा सहमति"),
    ("renewal", "Renewal", "नवीनीकरण"),
    ("majority_transfer", "Turning 18", "18 साल पूरे"),
    ("manual", "Started by hand", "हाथ से शुरू"),
    ("material_notice_change", "Notice changed", "सूचना बदली"),
    ("turning_18", "Someone turns 18", "कोई 18 साल का हुआ"),
    ("validity_expiry", "Consent about to expire", "सहमति समाप्त होने वाली"),
    ("retention_notice", "Data about to be deleted", "डेटा मिटने वाला"),
    ("no_processing", "Stop using their data", "उनका डेटा इस्तेमाल बंद"),
    ("erase", "Erase", "मिटाएँ"),
    ("legitimate_use", "Legitimate use", "वैध उपयोग"),
    ("legal_retention", "Keep, required by law", "रखें, क़ानून के अनुसार ज़रूरी"),
    ("hold_for_review", "Hold for review", "समीक्षा के लिए रोकें"),
    ("consent", "Consent", "सहमति"),
    ("legal_obligation", "Legal obligation", "क़ानूनी दायित्व"),
    # retention and deletion
    ("collection", "When collected", "इकट्ठा करते समय से"),
    ("relationship_ended", "When the programme stops serving them", "जब कार्यक्रम उनकी सेवा बंद करे"),
    ("anonymise", "Anonymise", "पहचान हटाएँ"),
    ("ask_processor_to_erase", "Ask the partner to erase", "साझेदार से मिटाने को कहें"),
    ("legal_hold_then_review", "Legal hold, then review", "क़ानूनी रोक, फिर समीक्षा"),
    ("hard_purge", "Delete completely", "पूरी तरह मिटाएँ"),
    ("legal_hold", "Legal hold", "क़ानूनी रोक"),
    ("days", "Days", "दिन"),
    ("months", "Months", "महीने"),
    ("years", "Years", "साल"),
    # breach and devices
    ("data_leak", "Data leak", "डेटा लीक"),
    ("lost_device", "Lost or stolen phone", "फ़ोन खोया या चोरी"),
    ("phishing", "Phishing", "फ़िशिंग"),
    ("ransomware", "Ransomware", "रैनसमवेयर"),
    ("unauthorised_access", "Unauthorised access", "बिना अनुमति पहुँच"),
    ("active", "Active", "चालू"),
    ("logged_out", "Signed out", "साइन आउट"),
    ("wipe_queued", "Wipe queued", "मिटाना बाकी"),
    ("wiped", "Wiped", "मिटा दिया"),
    ("lost", "Lost", "खो गया"),
    # message templates and attempts
    ("receipt", "Receipt", "रसीद"),
    ("confirmation", "Confirmation", "पुष्टि"),
    ("deferred_confirmation", "Confirm later", "बाद में पुष्टि"),
    ("withdrawal_confirmation", "Withdrawal done", "सहमति वापसी पूरी"),
    ("otp", "One-time code", "एक बार का कोड"),
    ("reminder", "Reminder", "याद दिलाना"),
    ("breach_notice", "Breach notice", "उल्लंघन की सूचना"),
    ("rights_update", "Request update", "अनुरोध पर अपडेट"),
    ("pending", "Pending", "बाकी"),
    ("failed", "Failed", "असफल"),
    ("allow", "Allowed", "अनुमति है"),
    ("deny", "Denied", "अनुमति नहीं"),
    # audit actions
    ("insert", "Created", "बनाया"),
    ("update", "Changed", "बदला"),
    ("submit", "Submitted", "जमा किया"),
    ("cancel", "Cancelled", "रद्द किया"),
    ("delete", "Deleted", "हटाया"),
]

# Sarvam voices (Anumati Settings > Voice).
VOICES = [(v, v.title(), hi) for v, hi in (
    ("priya", "प्रिया"), ("kavya", "काव्या"), ("neha", "नेहा"), ("ritu", "ऋतु"), ("pooja", "पूजा"),
    ("simran", "सिमरन"), ("shreya", "श्रेया"), ("rahul", "राहुल"), ("amit", "अमित"), ("rohan", "रोहन"),
    ("aditya", "आदित्य"), ("kabir", "कबीर"))]

# Capitalised dropdown values (statuses). Frappe already has Hindi for Open, Draft, Closed, Pending, ...
STATUSES = [
    ("Unmatched", None, "मिलान बाकी"),
    ("Awaiting Acknowledgement", None, "पुष्टि का इंतज़ार"),
    ("Live", None, "चालू"),
    ("Paused", None, "रुका हुआ"),
    ("Retired", None, "बंद"),
    ("Approved", None, "स्वीकृत"),
    ("Running", None, "चल रहा है"),
    ("Completed", None, "पूरा"),
    ("Assessing", None, "जाँच जारी"),
    ("Contained", None, "रोका गया"),
    ("Notifying", None, "सूचना दी जा रही है"),
    ("Reported", None, "रिपोर्ट किया"),
    ("Acknowledged", None, "पुष्टि मिली"),
    ("Overdue", None, "समय निकल गया"),
    ("On Hold", None, "रोका गया"),
    ("Notified", None, "सूचित"),
    ("Requested", None, "अनुरोध भेजा"),
    ("Data Fiduciary", None, "डेटा फ़िड्यूशियरी"),
    ("Significant Data Fiduciary", None, "महत्वपूर्ण डेटा फ़िड्यूशियरी"),
    ("Data Processor", None, "डेटा प्रोसेसर"),
    ("Missed Call", None, "मिस्ड कॉल"),
]

# Sidebar sections, cards, shortcuts, number cards and charts (tools/gen_desk.py).
MENU = [
    ("Today", None, "आज"),
    ("Beneficiaries", None, "लाभार्थी"),
    ("Programmes", None, "कार्यक्रम"),
    ("Analytics", None, "विश्लेषण"),
    ("Notices and Compliance", None, "सूचनाएँ और अनुपालन"),
    ("Setup", None, "सेटअप"),
    ("Requests board", None, "अनुरोध बोर्ड"),
    ("Inbox", None, "इनबॉक्स"),
    ("Find a receipt", None, "रसीद खोजें"),
    ("Beneficiary", None, "लाभार्थी"),
    ("Requests", None, "अनुरोध"),
    ("Consents", None, "सहमतियाँ"),
    ("Guardians", None, "अभिभावक"),
    ("Guardian", None, "अभिभावक"),
    ("People", None, "लोग"),
    ("Consent", None, "सहमति"),
    ("Consent records", None, "सहमति रिकॉर्ड"),
    ("Current consent per purpose", None, "हर उद्देश्य की वर्तमान सहमति"),
    ("Confirmation attempt", None, "पुष्टि का प्रयास"),
    ("Waiting for confirmation", None, "पुष्टि बाकी"),
    ("Re-consent", None, "दोबारा सहमति"),
    ("Re-consent campaign", None, "दोबारा सहमति अभियान"),
    ("Field phones", None, "फील्ड फ़ोन"),
    ("Field phone", None, "फील्ड फ़ोन"),
    ("Field team", None, "फील्ड टीम"),
    ("Notices", None, "सूचनाएँ"),
    ("Notice", None, "सूचना"),
    ("Breaches", None, "डेटा उल्लंघन"),
    ("Breach", None, "डेटा उल्लंघन"),
    ("Records of processing", None, "प्रोसेसिंग रिकॉर्ड"),
    ("Records of processing and DPIA", None, "प्रोसेसिंग रिकॉर्ड और DPIA"),
    ("Records and risk", None, "रिकॉर्ड और जोखिम"),
    ("Incidents and audit", None, "घटनाएँ और ऑडिट"),
    ("Audit log", None, "ऑडिट लॉग"),
    ("Access log (names and evidence)", None, "कौन देखा (नाम और सबूत)"),
    ("Record views", None, "रिकॉर्ड कब देखे गए"),
    ("Organisation", None, "संस्था"),
    ("Team", None, "टीम"),
    ("Messaging", None, "मैसेजिंग"),
    ("SMS and messaging", None, "SMS और मैसेजिंग"),
    ("Connected systems", None, "जुड़े हुए सिस्टम"),
    ("Field app", None, "फील्ड ऐप"),
    ("{} open", None, "{} खुले"),
    ("{} waiting", None, "{} बाकी"),
    ("Consents This Week", None, "इस हफ़्ते की सहमतियाँ"),
    ("Withdrawals This Week", None, "इस हफ़्ते सहमति वापसी"),
    ("Open Rights Requests", None, "खुले अनुरोध"),
    ("Unmatched Requests", None, "मिलान बाकी अनुरोध"),
    ("Notice Heard In Full", None, "पूरी सूचना सुनी"),
    ("Overdue Requests", None, "समय निकले अनुरोध"),
    ("Waiting For Confirmation", None, "पुष्टि बाकी"),
    ("Consents This Month", None, "इस महीने की सहमतियाँ"),
    ("Withdrawals This Month", None, "इस महीने सहमति वापसी"),
    ("Refused This Month", None, "इस महीने मना किया"),
    ("Phones Not Synced", None, "सिंक नहीं हुए फ़ोन"),
    ("Open Breaches", None, "खुले डेटा उल्लंघन"),
    ("Translations Not Reviewed", None, "समीक्षा बाकी अनुवाद"),
    ("Consent Events Per Week", "Consents per week", "हर हफ़्ते की सहमतियाँ"),
    ("Agreed By Purpose", "Agreed, by purpose", "उद्देश्य के अनुसार सहमति"),
    ("How People Consented", "How people consented", "लोगों ने सहमति कैसे दी"),
    ("How The Notice Was Given", "How the notice was given", "सूचना कैसे दी गई"),
    ("Consents By Field Worker", "Consents by field worker", "कार्यकर्ता के अनुसार सहमतियाँ"),
    ("Consents By Language", "Consents by language", "भाषा के अनुसार सहमतियाँ"),
    ("Requests By Type", "Requests by type", "प्रकार के अनुसार अनुरोध"),
    ("Needs attention", None, "ध्यान दें"),
    ("Recorded (30 Days)", "Recorded (30 days)", "दर्ज (30 दिन)"),
    ("Confirmed", None, "पुष्टि हुई"),
    ("Evidence Only", "Evidence only", "सिर्फ़ सबूत"),
    ("Waiting To Sync", "Waiting to sync", "सिंक बाकी"),
    ("Withdrawn (30 Days)", "Withdrawn (30 days)", "सहमति वापसी (30 दिन)"),
    ("Verification Pipeline", "Verification pipeline", "पुष्टि की स्थिति"),
    ("Withdrawals By Channel", "Withdrawals by channel", "माध्यम के अनुसार सहमति वापसी"),
    ("Programmes At A Glance", "Programmes at a glance", "कार्यक्रम एक नज़र में"),
    ("Hash chain verified {0}", None, "हैश शृंखला की जाँच {0} हुई"),
    ("Hash chain check FAILED. Tell the DPO now.", None, "हैश शृंखला की जाँच असफल। DPO को अभी बताएँ।"),
    ("Hash chain not checked yet (runs every night)", None, "हैश शृंखला की जाँच अभी नहीं हुई (हर रात होती है)"),
    ("No programmes yet.", None, "अभी कोई कार्यक्रम नहीं।"),
    ("draft", None, "मसौदा"),
    ("Not recorded", None, "दर्ज नहीं"),
    ("Set up Anumati", None, "अनुमति सेट करें"),
]

# Messages in the form, list and block scripts.
MESSAGES = [
    ("requests are past their due date", None, "अनुरोधों का समय निकल गया है"),
    ("requests need matching to a person", None, "अनुरोधों को व्यक्ति से मिलाना बाकी है"),
    ("breaches are open (72-hour clock)", None, "डेटा उल्लंघन खुले हैं (72 घंटे की घड़ी)"),
    ("consents are waiting for confirmation", None, "सहमतियों की पुष्टि बाकी है"),
    ("field phones have not synced for 2 days", None, "फील्ड फ़ोन 2 दिन से सिंक नहीं हुए"),
    ("translations are waiting for review", None, "अनुवादों की समीक्षा बाकी है"),
    ("Nothing needs attention right now.", None, "अभी किसी चीज़ पर ध्यान देने की ज़रूरत नहीं।"),
    ("Name or phone", None, "नाम या फ़ोन"),
    ("Name, phone number or receipt code", None, "नाम, फ़ोन नंबर या रसीद कोड"),
    ("No one found. Names match whole words, and phone numbers must be complete.", None,
     "कोई नहीं मिला। नाम पूरे शब्द से मिलता है, और फ़ोन नंबर पूरा होना चाहिए।"),
    ("Receipt code, e.g. AN-7K2Q9C", None, "रसीद कोड, जैसे AN-7K2Q9C"),
    ("Adult", None, "वयस्क"), ("Minor", None, "नाबालिग"), ("Merged", None, "मिला दिया"),
    ("Shared phone", None, "साझा फ़ोन"), ("No phone", None, "फ़ोन नहीं"),
    ("Granted", None, "सहमति दी"), ("Withdrawal", None, "सहमति वापसी"), ("Refused all", None, "सब के लिए मना"),
    ("Renewed", None, "नवीनीकरण"), ("Waiting", None, "बाकी"), ("Not synced", None, "सिंक नहीं"),
    ("Wipe queued", None, "मिटाना बाकी"), ("Wiped", None, "मिटा दिया"), ("Signed out", None, "साइन आउट"),
    ("Active", None, "चालू"), ("Overdue", None, "समय निकल गया"),
    ("{0} waiting to sync", None, "{0} सिंक होना बाकी"),
    ("Assigned to me", None, "मुझे सौंपे गए"),
    ("Who is this for?", None, "यह किसके लिए है?"),
    ("Match", None, "मिलाएँ"),
    ("Several people share this number. Call back or check the slip, then pick the person.", None,
     "यह नंबर कई लोगों का है। वापस कॉल करें या पर्ची देखें, फिर व्यक्ति चुनें।"),
    ("Person", None, "व्यक्ति"),
    ("Overdue by {0} days", None, "{0} दिन देर"), ("Due today", None, "आज तक"),
    ("{0} days left", None, "{0} दिन बाकी"), ("due {0}", None, "{0} तक"),
    ("Record withdrawal", None, "सहमति वापसी दर्ज करें"),
    ("Withdrawal recorded: {0}", None, "सहमति वापसी दर्ज: {0}"),
    ("Check signature", None, "हस्ताक्षर जाँचें"),
    ("Signature is valid", None, "हस्ताक्षर सही है"),
    ("Signature check failed", None, "हस्ताक्षर की जाँच असफल"),
    ("This record's signature does not verify. Tell the DPO.", None, "इस रिकॉर्ड का हस्ताक्षर सही नहीं है। DPO को बताएँ।"),
    ("This record is number {0} on the signed chain (key {1}). It has not been changed since it was recorded.", None,
     "यह रिकॉर्ड हस्ताक्षरित शृंखला में नंबर {0} है (कुंजी {1})। दर्ज होने के बाद से इसमें कोई बदलाव नहीं हुआ।"),
    ("Agreed to", None, "इनके लिए सहमति"), ("Said no to", None, "इनके लिए मना"), ("None", None, "कोई नहीं"),
    ("How", None, "कैसे"), ("Verified by", None, "पुष्टि"), ("Recorded by", None, "दर्ज करने वाले"),
    ("heard in full", None, "पूरी सुनी"),
    ("Evidence is in the Evidence tab. Hash, signature and chain position are in the Proof tab. This record can never be edited; a change of mind is a new record.", None,
     "सबूत 'सबूत' टैब में है। हैश, हस्ताक्षर और शृंखला 'प्रमाण' टैब में हैं। यह रिकॉर्ड कभी बदला नहीं जा सकता; राय बदलने पर नया रिकॉर्ड बनता है।"),
    ("Beneficiary: {0}", None, "लाभार्थी: {0}"),
    ("Consent today", None, "आज की सहमति"),
    ("waiting for confirmation", None, "पुष्टि बाकी"),
    ("Relationship ended", None, "संबंध समाप्त"),
    ("Board told now", None, "बोर्ड को अभी बताया"),
    ("Board told on {0}", None, "बोर्ड को {0} को बताया"),
    ("{0} hours left to tell the Data Protection Board (deadline {1})", None,
     "डेटा संरक्षण बोर्ड को बताने के लिए {0} घंटे बाकी (अंतिम समय {1})"),
    ("72-hour deadline passed {0} hours ago. Tell the Data Protection Board now.", None,
     "72 घंटे की समय-सीमा {0} घंटे पहले निकल गई। डेटा संरक्षण बोर्ड को अभी बताएँ।"),
    ("Report lost", None, "खोया हुआ बताएँ"),
    ("Can't publish yet", None, "अभी प्रकाशित नहीं हो सकता"),
    ("Add at least one purpose", None, "कम से कम एक उद्देश्य जोड़ें"),
    ("Rule 3: {0} is missing", None, "नियम 3: {0} नहीं है"),
    ("How to withdraw consent", None, "सहमति वापस कैसे लें"),
    ("How to exercise rights", None, "अपने अधिकारों का उपयोग कैसे करें"),
    ("How to complain to the Data Protection Board", None, "डेटा संरक्षण बोर्ड से शिकायत कैसे करें"),
    ("DPO or grievance contact", None, "DPO या शिकायत संपर्क"),
    ("Summary of security safeguards", None, "सुरक्षा उपायों का सार"),
    ("Preview", None, "पूर्वावलोकन"),
    ("Yes to all", None, "सब के लिए हाँ"), ("No to all", None, "सब के लिए ना"),
    ("View guardian document", None, "अभिभावक का दस्तावेज़ देखें"),
    ("Make natural audio", None, "प्राकृतिक आवाज़ में ऑडियो बनाएँ"),
    ("Record demo audio (Sarvam)", None, "डेमो ऑडियो रिकॉर्ड करें (Sarvam)"),
    ("Recording started. You'll get a message when it's done.", None, "रिकॉर्डिंग शुरू हो गई। पूरी होने पर संदेश मिलेगा।"),
    ("Starting…", None, "शुरू हो रहा है…"),
    ("Woman's voice", None, "महिला की आवाज़"),
    ("Man's voice", None, "पुरुष की आवाज़"),
    ("Have you listened to both recordings in full, and do they say exactly what the notice says?", None,
     "क्या आपने दोनों रिकॉर्डिंग पूरी सुनी हैं, और क्या वे ठीक वही कहती हैं जो सूचना में लिखा है?"),
    ("Make audio again", None, "ऑडियो फिर से बनाएँ"),
    ("Approve audio", None, "ऑडियो स्वीकृत करें"),
    ("Audio", None, "ऑडियो"),
    ("Audio notice", None, "ऑडियो सूचना"),
    ("Approved by {0}", None, "{0} ने स्वीकृत किया"),
    ("Recorded audio", None, "रिकॉर्ड की गई आवाज़"),
    ("Machine-made, not approved: not played in the field", None, "मशीन से बना, स्वीकृत नहीं: फील्ड में नहीं चलेगा"),
    ("Making audio… this can take a minute", None, "ऑडियो बन रहा है… एक मिनट लग सकता है"),
    ("Have you listened to the whole recording, and does it say exactly what the notice says?", None,
     "क्या आपने पूरी रिकॉर्डिंग सुनी है, और क्या वह ठीक वही कहती है जो सूचना में लिखा है?"),
]


def rows():
    for group in (RECORD_TYPES, CODES, VOICES, STATUSES, MENU, MESSAGES):
        yield from group


def write(lang, pick):
    seen, out = set(), []
    for key, en, hi in rows():
        value = pick(key, en, hi)
        if key in seen or not value or value == key:
            continue
        seen.add(key)
        out.append((key, value))
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, lang + ".csv"), "w", newline="", encoding="utf-8") as fh:
        csv.writer(fh, lineterminator="\n").writerows(sorted(out))
    return len(out)


if __name__ == "__main__":
    print("en", write("en", lambda k, en, hi: en))
    print("hi", write("hi", lambda k, en, hi: hi))
